import type { PromptEntry } from '../types';

/**
 * Original prompt journal inspired by TYOV's structure (memories, erosion, diary play).
 * All text is codex-w authored — not reproduced from Tim Hutchings' book.
 */
export const totvPrompts: PromptEntry[] = [
  // 1–12 origin / turning / early unlife
  { id: 1, tags: ['origin'], text: 'Write three fragments of your mortal childhood — smells, sounds, or a single face.', hint: 'Fills Experiences in a memory' },
  { id: 2, tags: ['origin'], text: 'Where were you born, and what did the horizon look like from there?' },
  { id: 3, tags: ['origin'], text: 'Who taught you your first trade or talent before the turning?', hint: 'Up to five skills on your sheet' },
  { id: 4, tags: ['origin'], text: 'Describe the night you stopped being human. What broke first — body or belief?', hint: 'Record as Experiences or diary' },
  { id: 5, tags: ['bond'], text: 'Name someone who loved you while you still aged. What promise did you make them?', hint: 'Up to five characters' },
  { id: 6, tags: ['gain'], text: 'Add a skill you learned in your first lonely century.', hint: 'Up to five skills on your sheet' },
  { id: 7, tags: ['gain'], text: 'Claim a resource you still protect — a house, hoard, relic, or refuge.', hint: 'Up to five resources' },
  { id: 8, tags: ['bond'], text: 'Introduce a mortal or monster who keeps pulling you back into the world.', hint: 'Up to five characters' },
  { id: 9, tags: ['diary'], text: 'Write a diary stanza about hunger — what you crave that blood cannot give.' },
  { id: 10, tags: ['gain'], text: 'Record a memory of beauty that survived the turning.', hint: 'Add an Experience to a memory (max three each)' },
  { id: 11, tags: ['bond'], text: 'A letter arrives decades late. Who wrote it, and what do they still believe about you?', hint: 'Character or diary' },
  { id: 12, tags: ['mark'], text: 'The turning left a Mark on you — a habit, scar, or change that never left.', hint: 'Fill a Mark slot' },

  // 13–40 centuries of pressure
  { id: 13, tags: ['loss'], text: 'You need room for something new. Strike a memory until only ash remains.', hint: 'Forget Experiences or clear a memory' },
  { id: 14, tags: ['loss'], text: 'A skill atrophies from disuse. Cross it out and name what replaced it in your life.', hint: 'Clear a skill slot' },
  { id: 15, tags: ['loss'], text: 'Spend a resource desperately. What did it buy, and who noticed the waste?', hint: 'Clear a resource slot' },
  { id: 16, tags: ['bond'], text: 'Someone you cherished forgets your face. How do you prove you existed?', hint: 'Character slot' },
  { id: 17, tags: ['diary'], text: 'Write about a war you watched from the edges. Whose side did you pretend to take?' },
  { id: 18, tags: ['gain'], text: 'Adopt a new name the world gives you. Why do you accept or reject it?', hint: 'Add an Experience to a memory' },
  { id: 19, tags: ['bond'], text: 'A fledgling asks for guidance. What lie do you tell them for their own good?', hint: 'Up to five characters' },
  { id: 20, tags: ['loss'], text: 'An old enemy dies of time, not your hand. What do you do with the victory?', hint: 'May clear a character' },
  { id: 21, tags: ['diary'], text: 'Describe a century you barely remember. What feeling lingers without facts?' },
  { id: 22, tags: ['gain'], text: 'Discover an art form born after your turning. Which piece undoes you?', hint: 'Add an Experience' },
  { id: 23, tags: ['bond'], text: 'A mortal saves you without knowing what you are. Do you repay them — and how?', hint: 'Character slot' },
  { id: 24, tags: ['loss'], text: 'Lose a character from your sheet: they move on, die, or refuse you.', hint: 'Clear a character slot' },
  { id: 25, tags: ['diary'], text: 'Write about the loneliest feast you ever attended.' },
  { id: 26, tags: ['gain'], text: 'Claim a territory — a district, ruin, or stretch of coast. What rules do you enforce?', hint: 'Up to five resources' },
  { id: 27, tags: ['bond'], text: 'Two people you care for collide. Whose pain do you choose to witness?', hint: 'Characters' },
  { id: 28, tags: ['loss'], text: 'Forget a skill on purpose to learn something monstrous. Name the trade-off.', hint: 'Clear a skill; may gain another later' },
  { id: 29, tags: ['diary'], text: 'A religion rises that would call you demon. How do you hide among its hymns?' },
  { id: 30, tags: ['bond'], text: 'Someone photographs you without consent. What does the image reveal?', hint: 'Character or Mark' },
  { id: 31, tags: ['loss'], text: 'Your last link to your birthplace is demolished. Salvage one detail before it vanishes.', hint: 'Forget or compress a memory' },
  { id: 32, tags: ['gain'], text: 'Forge a new resource out of patience — an investment that finally matures.', hint: 'Up to five resources' },
  { id: 33, tags: ['diary'], text: 'Write a confession you will never send.' },
  { id: 34, tags: ['bond'], text: 'A child shows you mercy. What do you do with that unbearable gift?', hint: 'Character slot' },
  { id: 35, tags: ['loss'], text: 'Erase a happy Experience to keep a darker one sharp. Why is the dark worth more?', hint: 'Forget an Experience' },
  { id: 36, tags: ['mark'], text: 'A new Mark settles in — something you cannot hide from yourself anymore.', hint: 'Fill a Mark slot' },
  { id: 37, tags: ['gain'], text: 'Learn a language that did not exist when you were mortal. Who taught you?', hint: 'Skill slot' },
  { id: 38, tags: ['bond'], text: 'An old rival becomes an ally for one night only. What do you ask of them?', hint: 'Character slot' },
  { id: 39, tags: ['loss'], text: 'A resource you trusted turns against you — sold, cursed, or emptied.', hint: 'Clear a resource' },
  { id: 40, tags: ['diary'], text: 'Record a decade of quiet. What almost made you believe you were still human?' },

  // 41–60 late erosion / ending pressure
  { id: 41, tags: ['gain'], text: 'You invent a new ritual to keep yourself from unraveling. Describe it.', hint: 'Experience or skill' },
  { id: 42, tags: ['bond'], text: 'Someone inherits your name without knowing you. Do you correct them?', hint: 'Character' },
  { id: 43, tags: ['loss'], text: 'Compress a crowded memory into a single dull fact. What detail do you mourn?', hint: 'Compress a memory' },
  { id: 44, tags: ['mark'], text: 'The world names your kind differently now. How does the new word Mark you?', hint: 'Mark slot' },
  { id: 45, tags: ['diary'], text: 'Describe the world one hundred years from now as you hope it will be — not as you expect.' },
  { id: 46, tags: ['bond'], text: 'A mortal chronicler wants your story. What false ending do you give them?', hint: 'Character' },
  { id: 47, tags: ['loss'], text: 'You misremember a face you loved. Clear or rewrite an Experience.', hint: 'Forget an Experience' },
  { id: 48, tags: ['gain'], text: 'Acquire a modern refuge — anonymity as architecture.', hint: 'Resource slot' },
  { id: 49, tags: ['diary'], text: 'Write about the last time you felt truly afraid of another vampire.' },
  { id: 50, tags: ['bond'], text: 'Someone you created returns to judge you. What verdict do they speak?', hint: 'Character' },
  { id: 51, tags: ['loss'], text: 'A Mark you carried fades — or you force it away. What goes with it?', hint: 'Clear a Mark' },
  { id: 52, tags: ['gain'], text: 'A skill from your mortal life resurfaces uselessly beautiful. Keep it anyway.', hint: 'Skill slot' },
  { id: 53, tags: ['diary'], text: 'List three cities you ruined softly, without meaning to.' },
  { id: 54, tags: ['mark'], text: 'Hunger carves a permanent Mark: a tell, a craving, a limit.', hint: 'Mark slot' },
  { id: 55, tags: ['loss'], text: 'You abandon a territory that once defined you. Clear the resource.', hint: 'Clear a resource' },
  { id: 56, tags: ['bond'], text: 'The last person who knew your human name dies. Who remains to contradict your lies?', hint: 'Character' },
  { id: 57, tags: ['gain'], text: 'Add one final Experience to a memory already strained with meaning.', hint: 'Experience in a memory' },
  { id: 58, tags: ['diary'], text: 'Write the letter you would leave if the sun finally took you.' },
  { id: 59, tags: ['loss'], text: 'Choose what you will not carry into the next century. Forget it.', hint: 'Forget Experiences or clear a slot' },
  { id: 60, tags: ['reflect'], text: 'You are still here. What tiny, stubborn reason keeps you from ending the story?', hint: 'Diary or Mark' },
];
